//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11-b140731.1112 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.23 at 12:48:57 PM EDT 
//

package mdc.transit.train.tracker;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for InfoType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="InfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="StationName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="StationID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="StationAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RiderAlert" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Facilities" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NB_Time1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NB_Time1_Est" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="NB_Time1_Arrival" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NB_Time1_Train" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="NB_Time1_LineID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NB_Time2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NB_Time2_Est" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="NB_Time2_Arrival" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NB_Time2_Train" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NB_Time2_LineID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NB_Time3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NB_Time3_Est" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="NB_Time3_Arrival" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NB_Time3_Train" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NB_Time3_LineID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SB_Time1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SB_Time1_Est" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="SB_Time1_Arrival" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SB_Time1_Train" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="SB_Time1_LineID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SB_Time2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SB_Time2_Est" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="SB_Time2_Arrival" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SB_Time2_Train" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="SB_Time2_LineID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SB_Time3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SB_Time3_Est" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="SB_Time3_Arrival" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SB_Time3_Train" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="SB_Time3_LineID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InfoType", propOrder = { "stationName", "stationID", "stationAddress", "riderAlert", "facilities",
		"nbTime1", "nbTime1Est", "nbTime1Arrival", "nbTime1Train", "nbTime1LineID", "nbTime2", "nbTime2Est",
		"nbTime2Arrival", "nbTime2Train", "nbTime2LineID", "nbTime3", "nbTime3Est", "nbTime3Arrival", "nbTime3Train",
		"nbTime3LineID", "sbTime1", "sbTime1Est", "sbTime1Arrival", "sbTime1Train", "sbTime1LineID", "sbTime2",
		"sbTime2Est", "sbTime2Arrival", "sbTime2Train", "sbTime2LineID", "sbTime3", "sbTime3Est", "sbTime3Arrival",
		"sbTime3Train", "sbTime3LineID" })
public class InfoType {

	@XmlElement(name = "StationName", required = true)
	protected String stationName;
	@XmlElement(name = "StationID", required = true)
	protected String stationID;
	@XmlElement(name = "StationAddress", required = true)
	protected String stationAddress;
	@XmlElement(name = "RiderAlert", required = true)
	protected String riderAlert;
	@XmlElement(name = "Facilities", required = true)
	protected String facilities;
	@XmlElement(name = "NB_Time1", required = true)
	protected String nbTime1;
	@XmlElement(name = "NB_Time1_Est")
	protected short nbTime1Est;
	@XmlElement(name = "NB_Time1_Arrival", required = true)
	protected String nbTime1Arrival;
	@XmlElement(name = "NB_Time1_Train")
	protected byte nbTime1Train;
	@XmlElement(name = "NB_Time1_LineID", required = true)
	protected String nbTime1LineID;
	@XmlElement(name = "NB_Time2", required = true)
	protected String nbTime2;
	@XmlElement(name = "NB_Time2_Est")
	protected short nbTime2Est;
	@XmlElement(name = "NB_Time2_Arrival", required = true)
	protected String nbTime2Arrival;
	@XmlElement(name = "NB_Time2_Train", required = true)
	protected String nbTime2Train;
	@XmlElement(name = "NB_Time2_LineID", required = true)
	protected String nbTime2LineID;
	@XmlElement(name = "NB_Time3", required = true)
	protected String nbTime3;
	@XmlElement(name = "NB_Time3_Est")
	protected short nbTime3Est;
	@XmlElement(name = "NB_Time3_Arrival", required = true)
	protected String nbTime3Arrival;
	@XmlElement(name = "NB_Time3_Train", required = true)
	protected String nbTime3Train;
	@XmlElement(name = "NB_Time3_LineID", required = true)
	protected String nbTime3LineID;
	@XmlElement(name = "SB_Time1", required = true)
	protected String sbTime1;
	@XmlElement(name = "SB_Time1_Est")
	protected short sbTime1Est;
	@XmlElement(name = "SB_Time1_Arrival", required = true)
	protected String sbTime1Arrival;
	@XmlElement(name = "SB_Time1_Train")
	protected byte sbTime1Train;
	@XmlElement(name = "SB_Time1_LineID", required = true)
	protected String sbTime1LineID;
	@XmlElement(name = "SB_Time2", required = true)
	protected String sbTime2;
	@XmlElement(name = "SB_Time2_Est")
	protected short sbTime2Est;
	@XmlElement(name = "SB_Time2_Arrival", required = true)
	protected String sbTime2Arrival;
	@XmlElement(name = "SB_Time2_Train")
	protected byte sbTime2Train;
	@XmlElement(name = "SB_Time2_LineID", required = true)
	protected String sbTime2LineID;
	@XmlElement(name = "SB_Time3", required = true)
	protected String sbTime3;
	@XmlElement(name = "SB_Time3_Est")
	protected short sbTime3Est;
	@XmlElement(name = "SB_Time3_Arrival", required = true)
	protected String sbTime3Arrival;
	@XmlElement(name = "SB_Time3_Train")
	protected byte sbTime3Train;
	@XmlElement(name = "SB_Time3_LineID", required = true)
	protected String sbTime3LineID;

	/**
	 * Gets the value of the stationName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStationName() {
		return stationName;
	}

	/**
	 * Sets the value of the stationName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setStationName(String value) {
		this.stationName = value;
	}

	/**
	 * Gets the value of the stationID property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStationID() {
		return stationID;
	}

	/**
	 * Sets the value of the stationID property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setStationID(String value) {
		this.stationID = value;
	}

	/**
	 * Gets the value of the stationAddress property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStationAddress() {
		return stationAddress;
	}

	/**
	 * Sets the value of the stationAddress property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setStationAddress(String value) {
		this.stationAddress = value;
	}

	/**
	 * Gets the value of the riderAlert property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRiderAlert() {
		return riderAlert;
	}

	/**
	 * Sets the value of the riderAlert property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRiderAlert(String value) {
		this.riderAlert = value;
	}

	/**
	 * Gets the value of the facilities property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getFacilities() {
		return facilities;
	}

	/**
	 * Sets the value of the facilities property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setFacilities(String value) {
		this.facilities = value;
	}

	/**
	 * Gets the value of the nbTime1 property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNBTime1() {
		return nbTime1;
	}

	/**
	 * Sets the value of the nbTime1 property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNBTime1(String value) {
		this.nbTime1 = value;
	}

	/**
	 * Gets the value of the nbTime1Est property.
	 * 
	 */
	public short getNBTime1Est() {
		return nbTime1Est;
	}

	/**
	 * Sets the value of the nbTime1Est property.
	 * 
	 */
	public void setNBTime1Est(short value) {
		this.nbTime1Est = value;
	}

	/**
	 * Gets the value of the nbTime1Arrival property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNBTime1Arrival() {
		return nbTime1Arrival;
	}

	/**
	 * Sets the value of the nbTime1Arrival property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNBTime1Arrival(String value) {
		this.nbTime1Arrival = value;
	}

	/**
	 * Gets the value of the nbTime1Train property.
	 * 
	 */
	public byte getNBTime1Train() {
		return nbTime1Train;
	}

	/**
	 * Sets the value of the nbTime1Train property.
	 * 
	 */
	public void setNBTime1Train(byte value) {
		this.nbTime1Train = value;
	}

	/**
	 * Gets the value of the nbTime1LineID property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNBTime1LineID() {
		return nbTime1LineID;
	}

	/**
	 * Sets the value of the nbTime1LineID property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNBTime1LineID(String value) {
		this.nbTime1LineID = value;
	}

	/**
	 * Gets the value of the nbTime2 property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNBTime2() {
		return nbTime2;
	}

	/**
	 * Sets the value of the nbTime2 property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNBTime2(String value) {
		this.nbTime2 = value;
	}

	/**
	 * Gets the value of the nbTime2Est property.
	 * 
	 */
	public short getNBTime2Est() {
		return nbTime2Est;
	}

	/**
	 * Sets the value of the nbTime2Est property.
	 * 
	 */
	public void setNBTime2Est(short value) {
		this.nbTime2Est = value;
	}

	/**
	 * Gets the value of the nbTime2Arrival property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNBTime2Arrival() {
		return nbTime2Arrival;
	}

	/**
	 * Sets the value of the nbTime2Arrival property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNBTime2Arrival(String value) {
		this.nbTime2Arrival = value;
	}

	/**
	 * Gets the value of the nbTime2Train property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNBTime2Train() {
		return nbTime2Train;
	}

	/**
	 * Sets the value of the nbTime2Train property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNBTime2Train(String value) {
		this.nbTime2Train = value;
	}

	/**
	 * Gets the value of the nbTime2LineID property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNBTime2LineID() {
		return nbTime2LineID;
	}

	/**
	 * Sets the value of the nbTime2LineID property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNBTime2LineID(String value) {
		this.nbTime2LineID = value;
	}

	/**
	 * Gets the value of the nbTime3 property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNBTime3() {
		return nbTime3;
	}

	/**
	 * Sets the value of the nbTime3 property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNBTime3(String value) {
		this.nbTime3 = value;
	}

	/**
	 * Gets the value of the nbTime3Est property.
	 * 
	 */
	public short getNBTime3Est() {
		return nbTime3Est;
	}

	/**
	 * Sets the value of the nbTime3Est property.
	 * 
	 */
	public void setNBTime3Est(short value) {
		this.nbTime3Est = value;
	}

	/**
	 * Gets the value of the nbTime3Arrival property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNBTime3Arrival() {
		return nbTime3Arrival;
	}

	/**
	 * Sets the value of the nbTime3Arrival property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNBTime3Arrival(String value) {
		this.nbTime3Arrival = value;
	}

	/**
	 * Gets the value of the nbTime3Train property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNBTime3Train() {
		return nbTime3Train;
	}

	/**
	 * Sets the value of the nbTime3Train property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNBTime3Train(String value) {
		this.nbTime3Train = value;
	}

	/**
	 * Gets the value of the nbTime3LineID property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNBTime3LineID() {
		return nbTime3LineID;
	}

	/**
	 * Sets the value of the nbTime3LineID property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNBTime3LineID(String value) {
		this.nbTime3LineID = value;
	}

	/**
	 * Gets the value of the sbTime1 property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSBTime1() {
		return sbTime1;
	}

	/**
	 * Sets the value of the sbTime1 property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSBTime1(String value) {
		this.sbTime1 = value;
	}

	/**
	 * Gets the value of the sbTime1Est property.
	 * 
	 */
	public short getSBTime1Est() {
		return sbTime1Est;
	}

	/**
	 * Sets the value of the sbTime1Est property.
	 * 
	 */
	public void setSBTime1Est(short value) {
		this.sbTime1Est = value;
	}

	/**
	 * Gets the value of the sbTime1Arrival property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSBTime1Arrival() {
		return sbTime1Arrival;
	}

	/**
	 * Sets the value of the sbTime1Arrival property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSBTime1Arrival(String value) {
		this.sbTime1Arrival = value;
	}

	/**
	 * Gets the value of the sbTime1Train property.
	 * 
	 */
	public byte getSBTime1Train() {
		return sbTime1Train;
	}

	/**
	 * Sets the value of the sbTime1Train property.
	 * 
	 */
	public void setSBTime1Train(byte value) {
		this.sbTime1Train = value;
	}

	/**
	 * Gets the value of the sbTime1LineID property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSBTime1LineID() {
		return sbTime1LineID;
	}

	/**
	 * Sets the value of the sbTime1LineID property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSBTime1LineID(String value) {
		this.sbTime1LineID = value;
	}

	/**
	 * Gets the value of the sbTime2 property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSBTime2() {
		return sbTime2;
	}

	/**
	 * Sets the value of the sbTime2 property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSBTime2(String value) {
		this.sbTime2 = value;
	}

	/**
	 * Gets the value of the sbTime2Est property.
	 * 
	 */
	public short getSBTime2Est() {
		return sbTime2Est;
	}

	/**
	 * Sets the value of the sbTime2Est property.
	 * 
	 */
	public void setSBTime2Est(short value) {
		this.sbTime2Est = value;
	}

	/**
	 * Gets the value of the sbTime2Arrival property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSBTime2Arrival() {
		return sbTime2Arrival;
	}

	/**
	 * Sets the value of the sbTime2Arrival property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSBTime2Arrival(String value) {
		this.sbTime2Arrival = value;
	}

	/**
	 * Gets the value of the sbTime2Train property.
	 * 
	 */
	public byte getSBTime2Train() {
		return sbTime2Train;
	}

	/**
	 * Sets the value of the sbTime2Train property.
	 * 
	 */
	public void setSBTime2Train(byte value) {
		this.sbTime2Train = value;
	}

	/**
	 * Gets the value of the sbTime2LineID property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSBTime2LineID() {
		return sbTime2LineID;
	}

	/**
	 * Sets the value of the sbTime2LineID property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSBTime2LineID(String value) {
		this.sbTime2LineID = value;
	}

	/**
	 * Gets the value of the sbTime3 property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSBTime3() {
		return sbTime3;
	}

	/**
	 * Sets the value of the sbTime3 property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSBTime3(String value) {
		this.sbTime3 = value;
	}

	/**
	 * Gets the value of the sbTime3Est property.
	 * 
	 */
	public short getSBTime3Est() {
		return sbTime3Est;
	}

	/**
	 * Sets the value of the sbTime3Est property.
	 * 
	 */
	public void setSBTime3Est(short value) {
		this.sbTime3Est = value;
	}

	/**
	 * Gets the value of the sbTime3Arrival property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSBTime3Arrival() {
		return sbTime3Arrival;
	}

	/**
	 * Sets the value of the sbTime3Arrival property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSBTime3Arrival(String value) {
		this.sbTime3Arrival = value;
	}

	/**
	 * Gets the value of the sbTime3Train property.
	 * 
	 */
	public byte getSBTime3Train() {
		return sbTime3Train;
	}

	/**
	 * Sets the value of the sbTime3Train property.
	 * 
	 */
	public void setSBTime3Train(byte value) {
		this.sbTime3Train = value;
	}

	/**
	 * Gets the value of the sbTime3LineID property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSBTime3LineID() {
		return sbTime3LineID;
	}

	/**
	 * Sets the value of the sbTime3LineID property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSBTime3LineID(String value) {
		this.sbTime3LineID = value;
	}

}
